name: CI
on:
  push:
  pull_request:
    types: [ opened ]

jobs:
  build:
    name: ğŸ§± build

    runs-on: ubuntu-latest
    container: docker://node:latest

    steps:
      - uses: actions/checkout@v2

      # install dependencies
      - name: Install Dependencies
        run: npm ci

      - name: format
        run: make format

      - name: ğŸ§± Build Typescript src
        run: make build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: ./lib

  test:
    name: ğŸ§ª test

    runs-on: ubuntu-latest
    container: docker://node:latest

    steps:
      - uses: actions/checkout@v2

      # install dependencies
      - name: Install Dependencies
        run: npm ci

      # run tests
      - name: ğŸ§ª Run Unit Tests
        run: make test-unit

  package:
    name: ğŸ“¦ package

    runs-on: ubuntu-latest
    container: docker://node:buster

    needs: build

#    if: ${{ github. }}

    steps:
#      - name: Install Container Dependencies
#        run: |
#          apt update
#          apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A1715D88E1DF1F24
#          apt install software-properties-common -y
#
#          add-apt-repository ppa:git-core/ppa -y
#          apt update
#          apt upgrade git

      - uses: actions/checkout@v2.3.3

      - name: Download lib from build job
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: ./lib

      # install dependencies
      - name: Install Dependencies
        run: npm ci

      - name: ğŸ§³ pack
        run: make package

      - run: ls -a $GITHUB_WORKSPACE

      - name: ğŸ™ push distribution package
        run: |
          git add ./dist/*
          git commit -m \"chore: package distribution\"
          git push